files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Models/ErrorViewModel.cs
namespace Inspinia.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/Auth1Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class Auth1Controller : Controller
    {
        public IActionResult LoginPin() => View();
        public IActionResult LockScreen() => View();
        public IActionResult TwoFactor() => View();
        public IActionResult ResetPass() => View();
        public IActionResult SignUp() => View();
        public IActionResult DeleteAccount() => View();
        public IActionResult NewPass() => View();
        public IActionResult SuccessMail() => View();
        public IActionResult SignIn() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/Auth2Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class Auth2Controller : Controller
    {
        public IActionResult LoginPin() => View();
        public IActionResult LockScreen() => View();
        public IActionResult TwoFactor() => View();
        public IActionResult ResetPass() => View();
        public IActionResult SignUp() => View();
        public IActionResult DeleteAccount() => View();
        public IActionResult NewPass() => View();
        public IActionResult SuccessMail() => View();
        public IActionResult SignIn() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/Auth3Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class Auth3Controller : Controller
    {
        public IActionResult LoginPin() => View();
        public IActionResult LockScreen() => View();
        public IActionResult TwoFactor() => View();
        public IActionResult ResetPass() => View();
        public IActionResult SignUp() => View();
        public IActionResult DeleteAccount() => View();
        public IActionResult NewPass() => View();
        public IActionResult SuccessMail() => View();
        public IActionResult SignIn() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Error400() => View();
        public IActionResult Error401() => View();
        public IActionResult Error403() => View();
        public IActionResult Error404() => View();
        public IActionResult Error408() => View();
        public IActionResult Error500() => View();
        public IActionResult Maintenance() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class LandingController : Controller
    {
        public IActionResult Index() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/LayoutsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class LayoutsController : Controller
    {
        public IActionResult Scrollable() => View();
        public IActionResult Boxed() => View();
        public IActionResult Preloader() => View();
        public IActionResult Horizontal() => View();
        public IActionResult Compact() => View();
        public IActionResult Outlook() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/PagesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class PagesController : Controller
    {
        public IActionResult Index() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/SidebarController.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class SidebarController : Controller
    {
        public IActionResult Image() => View();
        public IActionResult WithLines() => View();
        public IActionResult Compact() => View();
        public IActionResult IconView() => View();
        public IActionResult Offcanvas() => View();
        public IActionResult OnHoverActive() => View();
        public IActionResult OnHover() => View();
        public IActionResult NoIcons() => View();
        public IActionResult Light() => View();
        public IActionResult Gradient() => View();
        public IActionResult Gray() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/SkinController.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class SkinController : Controller
    {
        public IActionResult Minimal() => View();
        public IActionResult Flat() => View();
        public IActionResult Material() => View();
        public IActionResult Classic() => View();
        public IActionResult Modern() => View();
        public IActionResult Saas() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Controllers/TopbarController.cs
using Microsoft.AspNetCore.Mvc;

namespace Inspinia.Controllers
{
    public class TopbarController : Controller
    {
        public IActionResult SubItems() => View();
        public IActionResult Tools() => View();
        public IActionResult Dark() => View();
        public IActionResult Gradient() => View();
        public IActionResult Gray() => View();
    }
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Auth1/LockScreen.cshtml
@{
    ViewBag.Title = "LockScreen";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}


@section styles
{
}


    <div class="auth-box overflow-hidden align-items-center d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xxl-4 col-md-6 col-sm-8">
                    <div class="auth-brand text-center mb-4">
                        <a href=@Url.Action("Index", "Pages") class="logo-dark">
                            <img src="~/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a href=@Url.Action("Index", "Pages") class="logo-light">
                            <img src="~/images/logo.png" alt="logo" height="32">
                        </a>
                        <h4 class="fw-bold mt-3">Lock Screen! | IN+</h4>
                        <p class="text-muted w-lg-75 mx-auto">This screen is locked. Enter your password to continue</p>
                    </div>

                    <div class="card p-4 rounded-4">
                        <div class="text-center mb-4">
                            <img src="~/images/users/user-1.jpg" class="rounded-circle img-thumbnail avatar-xxl mb-2" alt="thumbnail">
                            <h5 class="fs-md">Damian D.</h5>
                        </div>

                        <form>

                            <div class="mb-3">
                                <label for="userPassword" class="form-label">Password <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="userPassword" placeholder="••••••••" required>
                                </div>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Unlock</button>
                            </div>
                        </form>

                        <p class="text-muted text-center mt-4 mb-0">
                            Not you? Return to <a href=@Url.Action("SignIn", "Auth1") class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                        </p>
                    </div>

                    <p class="text-center text-muted mt-4 mb-0">
                        © 2014 -
                        <script>document.write(new Date().getFullYear())</script> INSPINIA — by <span class="fw-semibold">WebAppLayers</span>
                    </p>
                </div>
            </div>
        </div>
    </div>


@section scripts
{
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Auth1/LoginPin.cshtml
@{
    ViewBag.Title = "LoginPin";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}


@section styles
{
}


    <div class="auth-box overflow-hidden align-items-center d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xxl-4 col-md-6 col-sm-8">
                    <div class="auth-brand text-center mb-4">
                        <a href=@Url.Action("Index", "Pages") class="logo-dark">
                            <img src="~/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a href=@Url.Action("Index", "Pages") class="logo-light">
                            <img src="~/images/logo.png" alt="logo" height="32">
                        </a>
                        <h4 class="fw-bold mt-3">Login with PIN! | IN+</h4>
                        <p class="text-muted w-lg-75 mx-auto">This screen is locked. Enter your PIN to continue.</p>
                    </div>

                    <div class="card p-4 rounded-4">
                        <div class="text-center mb-4">
                            <img src="~/images/users/user-1.jpg" class="rounded-circle img-thumbnail avatar-xxl mb-2" alt="thumbnail">
                            <h5 class="fs-md">Damian D.</h5>
                        </div>

                        <form>
                            <label class="form-label">Enter your 6-digit code <span class="text-danger">*</span></label>
                            <div class="d-flex gap-2 mb-3 two-factor">
                                <input type="text" class="form-control text-center" required>
                                <input type="text" class="form-control text-center" required>
                                <input type="text" class="form-control text-center" required>
                                <input type="text" class="form-control text-center" required>
                                <input type="text" class="form-control text-center" required>
                                <input type="text" class="form-control text-center" required>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Confirm</button>
                            </div>
                        </form>

                        <p class="text-muted text-center mt-4 mb-0">
                            Not you? Return to <a href=@Url.Action("SignIn", "Auth1") class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                        </p>
                    </div>

                    <p class="text-center text-muted mt-4 mb-0">
                        © 2014 -
                        <script>document.write(new Date().getFullYear())</script> INSPINIA — by <span class="fw-semibold">WebAppLayers</span>
                    </p>
                </div>
            </div>
        </div>
    </div>



@section scripts
{
   <!-- Two Factor Validator Js -->
    <script src="~/js/pages/auth-two-factor.js"></script>
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Auth1/NewPass.cshtml
@{
    ViewBag.Title = "NewPass";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}


@section styles
{
}




    <div class="auth-box overflow-hidden align-items-center d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xxl-4 col-md-6 col-sm-8">
                    <div class="auth-brand text-center mb-4">
                        <a href=@Url.Action("Index", "Pages") class="logo-dark">
                            <img src="~/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a href=@Url.Action("Index", "Pages") class="logo-light">
                            <img src="~/images/logo.png" alt="logo" height="32">
                        </a>
                        <h4 class="fw-bold mt-3">Setup New Password ! | IN+</h4>
                        <p class="text-muted w-lg-75 mx-auto">We've emailed you a 6-digit verification code. Please enter it below to confirm your email address</p>
                    </div>

                    <div class="card p-4 rounded-4">
                        <form>
                            <div class="mb-3">
                                <label for="userEmail" class="form-label">Email address <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="email" class="form-control" id="userEmail" placeholder="you@example.com" disabled>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label class="form-label">Enter your 6-digit code <span class="text-danger">*</span></label>
                                <div class="d-flex gap-2 two-factor">
                                    <input type="text" class="form-control text-center" required>
                                    <input type="text" class="form-control text-center" required>
                                    <input type="text" class="form-control text-center" required>
                                    <input type="text" class="form-control text-center" required>
                                    <input type="text" class="form-control text-center" required>
                                    <input type="text" class="form-control text-center" required>
                                </div>
                            </div>

                            <div class="mb-3" data-password="bar">
                                <label for="userPassword" class="form-label">Password <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="userPassword" placeholder="••••••••" required>
                                </div>

                                <div class="password-bar my-2"></div>
                                <p class="text-muted fs-xs mb-0">Use 8+ characters with letters, numbers & symbols.</p>
                            </div>

                            <div class="mb-3">
                                <label for="userNewPassword" class="form-label">Confirm New Password <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="userNewPassword" placeholder="••••••••" required>
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-check">
                                    <input class="form-check-input form-check-input-light fs-14" type="checkbox" id="termAndPolicy">
                                    <label class="form-check-label" for="termAndPolicy">Agree the Terms & Policy</label>
                                </div>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Update Password</button>
                            </div>

                        </form>

                        <p class="mt-4 text-muted text-center mb-4">Don’t have a code? <a href="#" class="text-decoration-underline link-offset-2 fw-semibold">Resend</a> or <a href="#" class="text-decoration-underline link-offset-2 fw-semibold">Call Us</a></p>
                        <p class="text-muted text-center mb-0">
                            Return to <a href=@Url.Action("SignIn", "Auth1") class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                        </p>
                    </div>

                    <p class="text-center text-muted mt-4 mb-0">
                        © 2014 -
                        <script>document.write(new Date().getFullYear())</script> INSPINIA — by <span class="fw-semibold">WebAppLayers</span>
                    </p>
                </div>
            </div>
        </div>
    </div>

@section scripts
{
  <!-- Two Factor Validator Js -->
    <script src="~/js/pages/auth-two-factor.js"></script>

    <!-- Password Suggestion Js -->
    <script src="~/js/pages/auth-password.js"></script>
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Auth1/ResetPass.cshtml
@{
    ViewBag.Title = "ResetPass";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}


@section styles
{
}


    <div class="auth-box overflow-hidden align-items-center d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xxl-4 col-md-6 col-sm-8">
                    <div class="auth-brand text-center mb-4">
                        <a href=@Url.Action("Index", "Pages") class="logo-dark">
                            <img src="~/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a href=@Url.Action("Index", "Pages") class="logo-light">
                            <img src="~/images/logo.png" alt="logo" height="32">
                        </a>
                        <h4 class="fw-bold mt-3">Forgot Password ? | IN+</h4>
                        <p class="text-muted w-lg-75 mx-auto">Enter your email address and we'll send you a link to reset your password.</p>
                    </div>

                    <div class="card p-4 rounded-4">
                        <form>
                            <div class="mb-3">
                                <label for="userEmail" class="form-label">Email address <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="email" class="form-control" id="userEmail" placeholder="you@example.com" required>
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="form-check">
                                    <input class="form-check-input form-check-input-light fs-14" type="checkbox" id="termAndPolicy">
                                    <label class="form-check-label" for="termAndPolicy">Agree the Terms & Policy</label>
                                </div>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Send Request</button>
                            </div>
                        </form>

                        <p class="text-muted text-center mt-4 mb-0">
                            Return to <a href=@Url.Action("SignIn", "Auth1") class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                        </p>
                    </div>

                    <p class="text-center text-muted mt-4 mb-0">
                        © 2014 -
                        <script>document.write(new Date().getFullYear())</script> INSPINIA — by <span class="fw-semibold">WebAppLayers</span>
                    </p>
                </div>
            </div>
        </div>
    </div>



@section scripts
{
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Auth1/SignIn.cshtml
@{
    ViewBag.Title = "SignIn";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

@section styles
{
}

<div class="auth-box overflow-hidden align-items-center d-flex">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-md-6 col-sm-8">
                <div class="auth-brand text-center mb-4">
                    <a href=@Url.Action("Index", "Pages") class="logo-dark">
                        <img src="~/images/logo-black.png" alt="dark logo" height="32">
                    </a>
                    <a href=@Url.Action("Index", "Pages") class="logo-light">
                        <img src="~/images/logo.png" alt="logo" height="32">
                    </a>
                    <h4 class="fw-bold mt-3">Welcome to IN+</h4>
                    <p class="text-muted w-lg-75 mx-auto">Let’s get you signed in. Enter your email and password to
                        continue.</p>
                </div>

                <div class="card p-4 rounded-4">
                    <form action="/">
                        <div class="mb-3">
                            <label for="userEmail" class="form-label">Email address <span
                                    class="text-danger">*</span></label>
                            <div class="input-group">
                                <input type="email" class="form-control" id="userEmail" placeholder="you@example.com"
                                    required>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="userPassword" class="form-label">Password <span
                                    class="text-danger">*</span></label>
                            <div class="input-group">
                                <input type="password" class="form-control" id="userPassword" placeholder="••••••••"
                                    required>
                            </div>
                        </div>

                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div class="form-check">
                                <input class="form-check-input form-check-input-light fs-14" type="checkbox"
                                    id="rememberMe">
                                <label class="form-check-label" for="rememberMe">Keep me signed in</label>
                            </div>
                            <a href=@Url.Action("ResetPass", "Auth1") class="text-decoration-underline link-offset-3 text-muted">Forgot
                                Password?</a>
                        </div>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary fw-semibold py-2">Sign In</button>
                        </div>
                    </form>

                    <p class="text-muted text-center mt-4 mb-0">
                        New here? <a href=@Url.Action("SignUp", "Auth1")
                            class="text-decoration-underline link-offset-3 fw-semibold">Create an account</a>
                    </p>
                </div>

                <p class="text-center text-muted mt-4 mb-0">
                    © 2014 -
                    <script>document.write(new Date().getFullYear())</script> INSPINIA — by <span
                        class="fw-semibold">WebAppLayers</span>
                </p>
            </div>
        </div>
    </div>
</div>


@section scripts
{
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Auth1/SignUp.cshtml
@{
    ViewBag.Title = "SignUp";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}


@section styles
{
   <!-- Password Suggestion Js -->
    <script src="~/js/pages/auth-password.js"></script>

}



    <div class="auth-box overflow-hidden align-items-center d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xxl-4 col-md-6 col-sm-8">
                    <div class="auth-brand text-center mb-4">
                        <a href=@Url.Action("Index", "Pages") class="logo-dark">
                            <img src="~/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a href=@Url.Action("Index", "Pages") class="logo-light">
                            <img src="~/images/logo.png" alt="logo" height="32">
                        </a>
                        <h4 class="fw-bold mt-3">Register to IN+</h4>
                        <p class="text-muted w-lg-75 mx-auto">Let’s get you started. Create your account by entering your details below.</p>
                    </div>

                    <div class="card p-4 rounded-4">
                        <form>
                            <div class="mb-3">
                                <label for="userName" class="form-label">Name <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="userName" placeholder="Damian D." required>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="userEmail" class="form-label">Email address <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="email" class="form-control" id="userEmail" placeholder="you@example.com" required>
                                </div>
                            </div>

                            <div class="mb-3" data-password="bar">
                                <label for="userPassword" class="form-label">Password <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="userPassword" placeholder="••••••••" required>
                                </div>
                                <div class="password-bar my-2"></div>
                                <p class="text-muted fs-xs mb-0">Use 8+ characters with letters, numbers & symbols.</p>
                            </div>

                            <div class="mb-3">
                                <div class="form-check">
                                    <input class="form-check-input form-check-input-light fs-14" type="checkbox" id="termAndPolicy">
                                    <label class="form-check-label" for="termAndPolicy">Agree the Terms & Policy</label>
                                </div>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Create Account</button>
                            </div>
                        </form>

                        <p class="text-muted text-center mt-4 mb-0">
                            Already have an account? <a href=@Url.Action("SignIn", "Auth1") class="text-decoration-underline link-offset-3 fw-semibold">Login</a>
                        </p>
                    </div>

                    <p class="text-center text-muted mt-4 mb-0">
                        © 2014 -
                        <script>document.write(new Date().getFullYear())</script> INSPINIA — by <span class="fw-semibold">WebAppLayers</span>
                    </p>
                </div>
            </div>
        </div>
    </div>

@section scripts
{
}

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Shared/Partials/_Footer.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 text-center text-md-start">
                © 2014 - <script>document.write(new Date().getFullYear())</script> Inspinia By <span class="fw-semibold">WebAppLayers</span>
            </div>
            <div class="col-md-6">
                <div class="text-md-end d-none d-md-block">
                    10GB of <span class="fw-bold">250GB</span> Free.
                </div>
            </div>
        </div>
    </div>
</footer>

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Shared/Partials/_FooterScripts.cshtml
<script src="~/js/vendors.min.js"></script>
<script src="~/js/app.js"></script>

files/INSPINIA_v4.2.0/ASP.Net-MVC5/Seed/Views/Shared/Partials/_HorizontalNav.cshtml
<!-- Horizontal Menu Start -->
<header class="topnav">
    <nav class="navbar navbar-expand-lg">
        <nav class="container-fluid">
            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Horizontal", "Layouts")>
                            <span class="menu-icon"><i class="ti ti-layout-dashboard"></i></span>
                            <span class="menu-text"> Dashboards </span>
                        </a>
                    </li>

                    <!-- Auth Version 1 Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle drop-arrow-none" href="#" id="topnav-auth-v1" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="menu-icon"><i class="ti ti-shield-lock"></i></span>
                            <span class="menu-text"> Menu Item </span>
                            <div class="menu-arrow"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-auth-v1">
                            <a href=@Url.Action("SignIn", "Auth1") class="dropdown-item">Menu Item Link</a>
                            <a href=@Url.Action("SignIn", "Auth1") class="dropdown-item">Menu Item Link</a>
                        </div>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle drop-arrow-none" href="#" id="topnav-layouts" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="menu-icon"><i class="ti ti-layout"></i></span>
                            <span class="menu-text">Multi Level Menu</span>
                            <div class="menu-arrow"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-layouts">
                            <div class="dropdown">
                                <a class="dropdown-item dropdown-toggle drop-arrow-none" href="#" id="topnav-layouts-one" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="ti ti-layout"></i> Layout Options <div class="menu-arrow"></div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="topnav-layouts-one">
                                    <a href=@Url.Action("SignIn", "Auth1") class="dropdown-item">Sub Item</a>
                                    <a href=@Url.Action("SignIn", "Auth1") class="dropdown-item">Sub Item</a>
                                </div>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Index", "Pages")>
                            <span class="menu-icon"><i class="ti ti-layout-sidebar"></i></span>
                            <span class="menu-text"> Vertical </span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </nav>
</header>
<!-- Horizontal Menu End -->